http:
  middlewares:
    cloudflarewarp:
      plugin:
        cloudflarewarp:
          disableDefault: false
    crowdsec: # crowdsec
      plugin:
        bouncer:
          enabled: true
#          LogLevel: DEBUG
          defaultDecisionSeconds: 60
          crowdsecMode: live
          crowdsecAppsecEnabled: true
          crowdsecAppsecHost: localhost:7422
          crowdsecAppsecFailureBlock: true
          crowdsecAppsecUnreachableBlock: true
          crowdsecLapiKey: "{{- with nomadVar "nomad/jobs/traefik" }}{{- .crowdsec_bouncer_token }}{{- end }}"
          crowdsecLapiHost: localhost:8080
          crowdsecLapiScheme: http
          crowdsecLapiTLSInsecureVerify: false
