http:
  routers:
    proxmox:
#      rule: Host(`proxmox.lab.${var.base_domain}`)
      rule: Host(`proxmox.lab.schoger.net`)
      service: proxmox@file
      entrypoints: websecure

  services:
    proxmox:
      weighted:
        healthCheck: {}
        services:
        - name: proxmox0
        - name: proxmox1
        - name: proxmox2

    proxmox0:
      loadBalancer:
        passHostHeader: true
        healthCheck:
          interval: 5s
          timeout: 2s
        servers:
          - url: "https://proxmox0.home:8006"

    proxmox1:
      loadBalancer:
        passHostHeader: true
        healthCheck:
          interval: 5s
          timeout: 2s
        servers:
          - url: "https://proxmox1.home:8006"

    proxmox2:
      loadBalancer:
        passHostHeader: true
        healthCheck:
          interval: 5s
          timeout: 2s
        servers:
          - url: "https://proxmox2.home:8006"
