version: "3.8"

# template for docker services which sit behind the Traefik proxy and mount storage via nfs from the NAS

services:
  SERVICE:
    image: org/SERVICE:latest
    container_name: SERVICE
    restart: unless-stopped

    networks:
      - traefik
    ports:
      - "80:80"

    volumes:
      - SERVICE:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

    environment: {}

    labels:
      traefik.enable: true
      traefik.http.routers.SERVICE.rule: Host(`SERVICE.lab.home`)
      traefik.http.routers.SERVICE.entrypoints: websecure
      traefik.http.routers.SERVICE.tls: true
      traefik.http.routers.SERVICE.tls.certResolver: home
      traefik.http.services.SERVICE.loadbalancer.server.port: 80

networks:
  traefik:
    name: traefik_network
    external: true

volumes:
  SERVICE:
    driver: local
    driver_opts:
      type: "nfs"
      device: ":/volume1/docker/SERVICE"
      o: "nfsvers=4,addr=storage.home,soft,nolock,noatime,rw"
