http:
  routers:
    consul:
      rule: Host(`consul.lab.schoger.net`)   # FIXME: not working yet, URL error
      service: consul@file
      entrypoints: websecure

  services:
    consul:
      loadBalancer:
        servers:
          - url: "http://master.home:8500"
          - url: "http://compute1.home:8500"
          - url: "http://compute2.home:8500"
