http:
  routers:
    consul:
#      rule: Host(`consul.lab.${var.base_domain}`)
      rule: Host(`consul.lab.schoger.net`)
      service: consul@file
      entrypoints: websecure

  services:
    consul:
      loadBalancer:
        servers:
          - url: "http://{{ env "attr.unique.network.ip-address" }}:8500"
