# Common middlewares dynamic configuration

http:
  middlewares:
    # middlewares for internet-facing services
    internet: 
      chain:
        middlewares:
          - secureHeaders
          - ddos_protection
  
    secureHeaders:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "strict-origin-when-cross-origin"
         # activate HSTS (HTTP Strict Transport Security)
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        
        customResponseHeaders:
          server: "" # prevent leaking the http server name 
        
        contentSecurityPolicy: default-src 'self'; frame-ancestors 'self'; base-uri 'self'; form-action 'self';
        
    ddos_protection:
      inFlightReq:
        amount: 10 # max 10 parallel requests
        sourceCriterion:
          ipStrategy:
            excludedIPs:
              - "192.168.0.0/16" # don't limit requests from internal clients
