http:
  routers:
    nomad:
#      rule: Host(`nomad.lab.{$var.base_domain}`)
      rule: Host(`nomad.lab.schoger.net`)
      service: nomad@file
      entrypoints: websecure

  services:
    nomad:
      loadBalancer:
        healthCheck:
          path: /v1/status/leader
          interval: 5s
          timeout: 2s
        servers:
          - url: "http://{{ env "attr.unique.network.ip-address" }}:4646"
