# static configuration 

providers:
  file:
    directory: "/local/conf"
    watch: false
  consulcatalog:
    prefix: "traefik"
    connectaware: true
    exposedByDefault: false
    servicename: "traefik-api" # connects Traefik to the Consul service
    endpoint:
      address: "http://consul.service.consul:8500"

certificatesResolvers:
  home:
    acme:
      caServer: "https://localhost:9443/acme/home/directory" # bound via Consul Connect
      email: "{{- with nomadVar "nomad/jobs/traefik" }}{{- .ca_email }}{{- end }}"
      storage: "{{ env "NOMAD_ALLOC_DIR" }}/data/home.json"
      tlsChallenge: true

entryPoints:
  # internal
  web:
    address: :80
    http:
      redirections: # global redirct to https
        entrypoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    http:
      tls: 
        options: strict_tls@file
        certResolver: home

  cloudflare: # from Cloudflare tunnel, just plain HTTP since the traffic is encryped by the CF tunnel and Consul Connect
    address: :1080

  # Traefik API
  traefik:
    address: :8080

serversTransport:
  insecureSkipVerify: true # trust internal TLS connection without cert validation
  rootCAs: 
    - {{ env "NOMAD_ALLOC_DIR" }}/data/intermediate_ca.crt
  
api:
  dashboard: true
  
ping:
  entryPoint: "traefik"

log:
  level: INFO
#  level: DEBUG

#accessLog: 
#  format: "<remote_IP_address> - <client_user_name_if_available> [<timestamp>] "<request_method> <request_path> <request_protocol>" <origin_server_HTTP_status> <origin_server_content_size> "<request_referrer>" "<request_user_agent>" <number_of_requests_received_since_Traefik_started> "<Traefik_router_name>" "<Traefik_server_URL>" <request_duration_in_ms>ms"
#  filePath: "/local/access.log"

metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true

global:
  sendanonymoususage: true # Periodically send anonymous usage statistics.
  
