# static configuration 

providers:
  file:
    directory: "/local/conf-home"
    watch: false
  consulcatalog:
    prefix: "traefik"
    watch: true # use watch instead of polling
    connectaware: true
    exposedByDefault: false
    servicename: "traefik-home-api" # connects Traefik to the Consul service
    endpoint:
      address: "http://consul.service.consul:8500"

certificatesResolvers:
  le:
    acme:
      email: "{{- with nomadVar "nomad/jobs/traefik" }}{{- .ca_email }}{{- end }}"
      storage: "{{ env "NOMAD_ALLOC_DIR" }}/data/le.json"
      caServer: https://acme-v02.api.letsencrypt.org/directory # prod (default)
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory # staging
      dnschallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

entryPoints:
  # redirect to https
  web:
    address: :80
    http:
      redirections: # global redirct to https
        entrypoint:
          to: websecure
          scheme: https
  # internal https with LE certificate
  websecure:
    address: :443
    http:
      tls:        # wildcard for the whole lab
        domains:    
          - main: lab.schoger.net
            sans:
              - "*.lab.schoger.net"
        options: strict_tls@file
        certResolver: le
  # Traefik API
  traefik:
    address: :8080

serversTransport:
  insecureSkipVerify: false # traffic is secured by Consul Connect
  
api:
  dashboard: true
  
ping:
  entryPoint: "traefik"

log:
  level: INFO
#  level: DEBUG

metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true

global:
  sendanonymoususage: true # Periodically send anonymous usage statistics.
  
