providers:
  file:
    directory: "/local/conf-dmz"
    watch: false
  consulcatalog:
    prefix: "dmz"
    connectaware: true
    exposedByDefault: false
    servicename: "traefik-dmz-api" # connects Traefik to the Consul service
    endpoint:
      address: "http://consul.service.consul:8500"

experimental:
  plugins:
    bouncer:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.3.5
    cloudflarewarp:
      modulename: github.com/BetterCorp/cloudflarewarp
      version: v1.3.3

entryPoints:
  cloudflare:
    address: :80
    http:
      middlewares:
        - cloudflarewarp@file # will rewrite the ClientHost field in the access log with the real IP of the client
        - crowdsec@file       # crowdsec bouncer
    forwardedHeaders:
      trustedIPs:
        - 127.0.0.1/32 # localhost because of Consul Connect SDN
  traefik:
    address: :1080

tls:
  certificates:
    - certFile: /secrets/certs/origin/schoger.net.crt
      keyFile: /secrets/certs/origin/schoger.net.key
    # - certFile: {{env "NOMAD_SECRETS_DIR"}}/certs/origin/{{env "BASE_DOMAIN"}}.crt
    #   keyFile: {{env "NOMAD_SECRETS_DIR"}}/certs/origin/{{env "BASE_DOMAIN"}}.key

api:
  dashboard: true
  insecure: true

ping:
  entryPoint: "traefik"

log:
  level: INFO
#  level: DEBUG

accessLog:         # access log will be analyzed by CrowdSec middleware
  filePath: {{ env "NOMAD_ALLOC_DIR" }}/traefik/access.log # Traefik access log location
  format: json
  filters:
    statusCodes:
      - "200-299"  # log successful http requests
      - "400-599"  # log failed http requests
  bufferingSize: 0 # don't collect logs as in-memory buffer before writing into log file
  fields:
    headers:
      defaultMode: keep
      names: # don't log overly chatty or sensitive headers
        Authorization: drop
        Cookie: drop
        Content-Security-Policy: drop
        Permissions-Policy: drop
        cf_clearance: drop

metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true

global:
  sendanonymoususage: true # Periodically send anonymous usage statistics.
